version: '3.8'

services:
  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 211228
      MYSQL_DATABASE: movil
    ports:
      - "3307:3306"

  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - "4000:4000"
    env_file:
      - .env
    command: npm start
